GITHUB_TOKEN = "ghp_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
GITHUB_REPO = "your-username/your-repo"
STREAMLIT_CLOUD = "true"  # Optional, to indicate Streamlit Cloud environment
GOOGLE_API_KEY = "your-google-api-key"  # Existing key
MISTRAL_API_KEY = "your-mistral-api-key"  # Existing key
DEEPSEEK_API_KEY = "your-deepseek-api-key"  # Existing key